### ISSUE TITLE
whats the password?

### ISSUE THREAD

**Issue by Vedant-Golait** [nikolatechie/ShopFX#1]
I was actually trying to create a new user account and was trying to use it as a reference for my new project. but i was stuck when it asked for user account and password can you help me out? 
Contact Information - vedantgolait04@gmail.com

**Comment by nikolatechie** [comment]
@Vedant-Golait  Hi. You can create a new user by hashing name and password using Java's `hashCode()` method. Then, add them to the `employees.txt` separated by a comma.
